version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
      target: backend
    working_dir: /workspace/chat-app/backend
    ports:
      - '4000:3000'
      - '6666:5555' # Prisma Studioのポート
    volumes:
      - .:/workspace/chat-app/:cached
      - backend_node_modules:/workspace/chat-app/backend/node_modules
    command: sh -lc "pnpm install && pnpm prisma generate && pnpm start:dev"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatdb

  frontend:
    build:
      context: .
      dockerfile: dockerfile
      target: frontend
    working_dir: /workspace/chat-app/frontend
    ports:
      - '4001:3000'
    volumes:
      - .:/workspace/chat-app/:cached
      - frontend_node_modules:/workspace/chat-app/frontend/node_modules
    command: sh -lc "pnpm install && pnpm dev"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  backend_node_modules:
  frontend_node_modules:
    # node_modulesをボリュームにすることで、ホストとコンテナ間での依存関係の不整合を防ぐ